// Hello, TypeScript! @jdomingu19
// Intensive Course by @midudev (2023)
// 026 Template Literal Types With crypto.randomUUID

// 1. Define template literal type for UUID-like structure
type HeroId = `${string}-${string}-${string}-${string}-${string}`;

// 2. Define type alias with readonly optional HeroId
type Hero = {
  readonly id?: HeroId;
  name: string;
  age: number;
  isActive?: boolean;
};

// 3. Create object with valid UUID generated by crypto.randomUUID()
let link1: Hero = {
  // Error: Type '"123-abc"' is not assignable to type '`${string}-${string}-${string}-${string}-${string}`'.
  // id: "123-abc",
  id: crypto.randomUUID(),
  name: "Link",
  age: 21,
  isActive: true,
};

// 4. Log object and inspect type
console.log(link1); // { id: 'f11f2037-5ac5-4a97-a21e-a730fa765284', name: 'Link', age: 21, isActive: true }
console.log(typeof link1); // object

console.log(link1.id); // f11f2037-5ac5-4a97-a21e-a730fa765284
console.log(typeof link1.id); // string

console.log(link1.id?.toString()); // f11f2037-5ac5-4a97-a21e-a730fa765284
console.log(typeof link1.id?.toString()); // string

// 5. Function returning object with UUID typed as HeroId
function createHero(hero: Hero): Hero {
  const { name, age } = hero;
  return {
    // Error: Type '"123-acb"' is not assignable to type '`${string}-${string}-${string}-${string}-${string}`'.
    // id: "123-acb",
    id: crypto.randomUUID(),
    name,
    age,
    isActive: true,
  };
}

// 6. Create object using function with type alias
const link2 = createHero({ name: "Link", age: 21 });

// 7. Log object and inspect type
console.log(link2); // { id: '369e9480-3c2f-4b52-8708-d729675ca98e', name: 'Link', age: 21, isActive: true }
console.log(typeof link2); // object

console.log(link2.id); // 369e9480-3c2f-4b52-8708-d729675ca98e
console.log(typeof link2.id); // string

console.log(link2.id?.toString()); // 369e9480-3c2f-4b52-8708-d729675ca98e
console.log(typeof link2.id?.toString()); // string
