"use strict";
(function () {
    var addTwoNumbers = function (a, b) { return a + b; };
    var greetUser = function (name) { return "Hello, ".concat(name, "!"); };
    var showMessage = function () { return "Hello, TypeScript!"; };
    var anyVariable;
    anyVariable = "abc";
    console.log({ anyVariable: anyVariable });
    console.log(typeof anyVariable);
    anyVariable = 42;
    console.log({ anyVariable: anyVariable });
    console.log(typeof anyVariable);
    anyVariable = true;
    console.log({ anyVariable: anyVariable });
    console.log(typeof anyVariable);
    anyVariable = addTwoNumbers;
    console.log(anyVariable(5, 6));
    anyVariable = greetUser;
    console.log(anyVariable("Jesús"));
    anyVariable = showMessage;
    console.log(anyVariable());
    var functionVariable;
    functionVariable = addTwoNumbers;
    console.log(functionVariable(5, 6));
    functionVariable = greetUser;
    console.log(functionVariable("Jesús"));
    functionVariable = showMessage;
    console.log(functionVariable());
    var a;
    a = addTwoNumbers;
    console.log(a(5, 6));
    var b;
    b = greetUser;
    console.log(b("Jesús"));
    b = showMessage;
    console.log(b("abc"));
    var c;
    c = showMessage;
    console.log(c());
})();
//# sourceMappingURL=function-type.js.map