"use strict";
(function () {
    function clearArray(array) {
        var i = array.length;
        while (i >= 0) {
            array.pop();
            i--;
        }
        return;
    }
    var myArray1 = [1, 2, 3, 4, 5];
    console.log({ myArray1: myArray1 });
    console.log(typeof myArray1);
    var myArray2 = ["a", "b", "c"];
    console.log({ myArray2: myArray2 });
    console.log(typeof myArray2);
    var myArray3 = ["1", 2, "3", 4, "5"];
    console.log({ myArray3: myArray3 });
    console.log(typeof myArray3);
    var myArray4 = [1, 2, 3, 4, 5];
    console.log({ myArray4: myArray4 });
    console.log(typeof myArray4);
    myArray4 = [6, 7, 8, 9, 10];
    console.log({ myArray4: myArray4 });
    console.log(typeof myArray4);
    var myArray5 = ["a", "b", "c"];
    console.log({ myArray5: myArray5 });
    console.log(typeof myArray5);
    myArray5 = ["d", "e", "f"];
    console.log({ myArray5: myArray5 });
    console.log(typeof myArray5);
    var myArray6 = [1, 2, 3, 4, 5];
    console.log({ myArray6: myArray6 });
    console.log(typeof myArray6);
    myArray6 = ["a", "b", "c"];
    console.log({ myArray6: myArray6 });
    console.log(typeof myArray6);
    var myArray7 = [1, 2, 3, 4, 5];
    console.log({ myArray7: myArray7 });
    console.log(typeof myArray7);
    myArray7 = ["a", "b", "c"];
    console.log({ myArray7: myArray7 });
    console.log(typeof myArray7);
    myArray7 = [1, 2, 3, "a", "b", "c"];
    console.log({ myArray7: myArray7 });
    console.log(typeof myArray7);
    var myArray8 = [1, 2, 3, 4, 5];
    console.log({ myArray8: myArray8 });
    console.log(typeof myArray8);
    var myArray9 = ["a", "b", "c"];
    console.log({ myArray9: myArray9 });
    console.log(typeof myArray9);
    var myArray10 = ["1", 2, "3", 4, "5"];
    console.log({ myArray10: myArray10 });
    console.log(typeof myArray10);
    var myArray11 = [1, 2, 3, 4, 5];
    console.log({ myArray11: myArray11 });
    console.log(typeof myArray11);
    clearArray(myArray11);
    myArray11.push(6, 7, 8, 9, 10);
    console.log({ myArray11: myArray11 });
    console.log(typeof myArray11);
    var myArray12 = ["a", "b", "c"];
    console.log({ myArray12: myArray12 });
    console.log(typeof myArray12);
    clearArray(myArray12);
    myArray12.push("d", "e", "f");
    console.log({ myArray12: myArray12 });
    console.log(typeof myArray12);
    var myArray13 = [1, 2, 3, 4, 5];
    console.log({ myArray13: myArray13 });
    console.log(typeof myArray13);
    var myArray14 = [1, 2, 3, 4, 5];
    console.log({ myArray14: myArray14 });
    console.log(typeof myArray14);
    clearArray(myArray14);
    myArray14.push("a", "b", "c");
    console.log({ myArray14: myArray14 });
    console.log(typeof myArray14);
    clearArray(myArray14);
    myArray14.push(1, 2, 3, "a", "b", "c");
    console.log({ myArray14: myArray14 });
    console.log(typeof myArray14);
    var stringArray = ["a", "b", "c"];
    stringArray.forEach(function (name) {
        console.log(name.toLocaleUpperCase());
    });
    var numberArray = [1, 2, 3, 4, 5];
    numberArray.forEach(function (name) {
        console.log(name.toFixed(1));
    });
})();
//# sourceMappingURL=arrays.js.map