"use strict";
(function () {
    var maybeBoolean;
    console.log(maybeBoolean);
    console.log(typeof maybeBoolean);
    console.log({ maybeBoolean: maybeBoolean });
    maybeBoolean = true;
    console.log(maybeBoolean);
    console.log(typeof maybeBoolean);
    console.log({ maybeBoolean: maybeBoolean });
    var definitelyBoolean;
    definitelyBoolean = true;
    console.log(definitelyBoolean);
    console.log(typeof definitelyBoolean);
    console.log({ definitelyBoolean: definitelyBoolean });
    definitelyBoolean = false;
    console.log(definitelyBoolean);
    console.log(typeof definitelyBoolean);
    console.log({ definitelyBoolean: definitelyBoolean });
    var isHero = true;
    var link;
    link = isHero ? "Hero of Time" : "Young Villager";
    console.log({ isHero: isHero });
    console.log({ link: link });
    console.log(typeof { isHero: isHero });
    console.log(typeof { link: link });
    console.log(typeof isHero);
    console.log(typeof link);
})();
//# sourceMappingURL=booleans.js.map