"use strict";
(function () {
    var _a, _b;
    var myString = "Hello, TypeScript!";
    console.log({ myString: myString });
    console.log(typeof myString);
    var myString2 = "Hello, Node.js!";
    console.log({ myString2: myString2 });
    console.log(typeof myString2);
    var myString3 = "He's often called @jdomingu19";
    console.log({ myString3: myString3 });
    console.log(typeof myString3);
    var myString4 = 'He"s often called @jdomingu19';
    console.log({ myString4: myString4 });
    console.log(typeof myString4);
    var myString5 = 'He\'s often called "@jdomingu19"';
    console.log({ myString5: myString5 });
    console.log(typeof myString5);
    var myString6 = "He's often called \"@jdomingu19\"";
    console.log({ myString6: myString6 });
    console.log(typeof myString6);
    var myString7 = "abc";
    console.log({ myString7: myString7 });
    console.log(typeof myString7);
    console.log(myString7.toUpperCase());
    console.log(typeof myString7.toUpperCase());
    var myAlias = "@jdomingu19";
    console.log("He's often called \"".concat(myAlias, "\""));
    console.log({ myAlias: myAlias });
    console.log(typeof myAlias);
    var myNumber = 42;
    console.log({ myNumber: myNumber });
    console.log(typeof myNumber);
    var x = myNumber.toString();
    console.log({ x: x });
    console.log(typeof x);
    console.log("".concat(myNumber, " and ").concat(myNumber.toString(), " in templated string are the same"));
    var myName = "Jesús";
    console.log({ myName: myName });
    console.log(typeof myName);
    console.log(myName.length);
    console.log(typeof myName.length);
    console.log(myName.toLocaleUpperCase());
    console.log(myName[0].toLocaleUpperCase());
    console.log(myName[1].toLocaleUpperCase());
    console.log(myName[2].toLocaleUpperCase());
    console.log(myName[3].toLocaleUpperCase());
    console.log(myName[4].toLocaleUpperCase());
    console.log(myName[5]);
    console.log((_a = myName[5]) === null || _a === void 0 ? void 0 : _a.toLocaleUpperCase());
    var defaultMessage = "String '".concat(myName, "' is indexed from 0 to ").concat(myName.length - 1);
    console.log(((_b = myName[5]) === null || _b === void 0 ? void 0 : _b.toLocaleUpperCase()) || defaultMessage);
})();
//# sourceMappingURL=strings.js.map